windows_stuff() {
	# generated by Git for Windows
	test -f ~/.profile && . ~/.profile
	test -f ~/.bashrc && . ~/.bashrc

	#hook script for the broot cli file explorer
	broot_bash=~/AppData/Roaming/dystroy/broot/config/launcher/bash/br
	if test -f $broot_bash ; then
		source $broot_bash
	fi
}

if [[ $OS -eq "Windows_NT" ]]; then
	windows_stuff
fi
